# TCL File Generated by Component Editor 13.1.1
# Mon Apr 11 16:16:09 EDT 2016
# DO NOT MODIFY


# 
# conway_multiple "conway_multiple" v1.0
#  2016.04.11.16:16:09
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module conway_multiple
# 
set_module_property DESCRIPTION ""
set_module_property NAME conway_multiple
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME conway_multiple
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Conway_Multiple
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file conway_multiple.sv SYSTEM_VERILOG PATH conway_multiple.sv TOP_LEVEL_FILE
add_fileset_file conway_single.sv SYSTEM_VERILOG PATH conway_single.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 22
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink left_col data Input 22


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 20
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source result data Output 20


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_streaming_sink_1
# 
add_interface avalon_streaming_sink_1 avalon_streaming end
set_interface_property avalon_streaming_sink_1 associatedClock clock
set_interface_property avalon_streaming_sink_1 associatedReset reset
set_interface_property avalon_streaming_sink_1 dataBitsPerSymbol 22
set_interface_property avalon_streaming_sink_1 errorDescriptor ""
set_interface_property avalon_streaming_sink_1 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_1 maxChannel 0
set_interface_property avalon_streaming_sink_1 readyLatency 0
set_interface_property avalon_streaming_sink_1 ENABLED true
set_interface_property avalon_streaming_sink_1 EXPORT_OF ""
set_interface_property avalon_streaming_sink_1 PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_1 center_col data Input 22


# 
# connection point avalon_streaming_sink_2
# 
add_interface avalon_streaming_sink_2 avalon_streaming end
set_interface_property avalon_streaming_sink_2 associatedClock clock
set_interface_property avalon_streaming_sink_2 associatedReset reset
set_interface_property avalon_streaming_sink_2 dataBitsPerSymbol 22
set_interface_property avalon_streaming_sink_2 errorDescriptor ""
set_interface_property avalon_streaming_sink_2 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_2 maxChannel 0
set_interface_property avalon_streaming_sink_2 readyLatency 0
set_interface_property avalon_streaming_sink_2 ENABLED true
set_interface_property avalon_streaming_sink_2 EXPORT_OF ""
set_interface_property avalon_streaming_sink_2 PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_2 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_2 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_2 right_col data Input 22


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

