# TCL File Generated by Component Editor 13.1.1
# Mon Apr 11 15:00:44 EDT 2016
# DO NOT MODIFY


# 
# tmemory "tmemory" v1.0
#  2016.04.11.15:00:44
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module tmemory
# 
set_module_property DESCRIPTION ""
set_module_property NAME tmemory
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME tmemory
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tmemory
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file tmemory.v VERILOG PATH tmemory.v TOP_LEVEL_FILE
add_fileset_file tmemory_bb.v VERILOG PATH tmemory_bb.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point a
# 
add_interface a avalon end
set_interface_property a addressUnits WORDS
set_interface_property a associatedClock clock_sink
set_interface_property a associatedReset ""
set_interface_property a bitsPerSymbol 8
set_interface_property a burstOnBurstBoundariesOnly false
set_interface_property a burstcountUnits WORDS
set_interface_property a explicitAddressSpan 0
set_interface_property a holdTime 0
set_interface_property a linewrapBursts false
set_interface_property a maximumPendingReadTransactions 0
set_interface_property a readLatency 0
set_interface_property a readWaitTime 1
set_interface_property a setupTime 0
set_interface_property a timingUnits Cycles
set_interface_property a writeWaitTime 0
set_interface_property a ENABLED true
set_interface_property a EXPORT_OF ""
set_interface_property a PORT_NAME_MAP ""
set_interface_property a CMSIS_SVD_VARIABLES ""
set_interface_property a SVD_ADDRESS_GROUP ""

add_interface_port a address_a address Input 16
set_interface_assignment a embeddedsw.configuration.isFlash 0
set_interface_assignment a embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment a embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment a embeddedsw.configuration.isPrintableDevice 0


# 
# connection point b
# 
add_interface b avalon end
set_interface_property b addressUnits WORDS
set_interface_property b associatedClock clock_sink_1
set_interface_property b associatedReset ""
set_interface_property b bitsPerSymbol 8
set_interface_property b burstOnBurstBoundariesOnly false
set_interface_property b burstcountUnits WORDS
set_interface_property b explicitAddressSpan 0
set_interface_property b holdTime 0
set_interface_property b linewrapBursts false
set_interface_property b maximumPendingReadTransactions 0
set_interface_property b readLatency 0
set_interface_property b readWaitTime 1
set_interface_property b setupTime 0
set_interface_property b timingUnits Cycles
set_interface_property b writeWaitTime 0
set_interface_property b ENABLED true
set_interface_property b EXPORT_OF ""
set_interface_property b PORT_NAME_MAP ""
set_interface_property b CMSIS_SVD_VARIABLES ""
set_interface_property b SVD_ADDRESS_GROUP ""

add_interface_port b address_b address Input 16
set_interface_assignment b embeddedsw.configuration.isFlash 0
set_interface_assignment b embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment b embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment b embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ""
set_interface_property avalon_slave_0 associatedReset ""
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 data_b writebyteenable_n Input 20
add_interface_port avalon_slave_0 wren_b writeresponserequest_n Input 1
add_interface_port avalon_slave_0 q_b readdata Output 20
add_interface_port avalon_slave_0 data_a writebyteenable_n Input 20
add_interface_port avalon_slave_0 wren_a writeresponserequest_n Input 1
add_interface_port avalon_slave_0 q_a readdata Output 20
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_a clk Input 1


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true
set_interface_property clock_sink_1 EXPORT_OF ""
set_interface_property clock_sink_1 PORT_NAME_MAP ""
set_interface_property clock_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_1 clock_b clk Input 1

